server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
#          uri: file:\Users\Admin\IdeaProjects\config
          uri: https://github.com/Jseongwon/spring-msa-config.git
#          username: [your username]
#          password: [your password]